#!/usr/bin/env sh

git diff --cached --name-only --diff-filter=ACMR -z -- 'apps/web' | xargs -0r ./apps/web/node_modules/.bin/prettier --write --ignore-unknown
git diff --cached --name-only --diff-filter=ACMR -z -- 'apps/web' | xargs -0r git add --
