apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bagtag.fullname" . }}-secrets
  labels:
    {{- include "bagtag.labels" . | nindent 4 }}
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: {{ include "bagtag.databasePassword" . | quote }}
  RESEND_API_KEY: {{ .Values.api.resend.apiKey | quote }}
